### ISSUE TITLE
Update to bootstrap 3

### ISSUE THREAD

**Issue by hariharan-uno** [Kotti/deform_bootstrap#66]
As bootstrap3 was released long back, i think it will be good if this project is updated to bs3.

**Comment by dairiki** [comment]
The latest alpha release of deform  ([2.0a1](https://pypi.python.org/pypi/deform/2.0a1)) uses bootstrap 3.

**Comment by scott2b** [comment]
Although, it does not seem like all widgets have been updated to bootstrap 3. E.g. CheckedPassword does not seem to render correctly. Is there a list of which widgets have been updated in 2.0a1?

**Comment by dairiki** [comment]
I don't know if there’s a list, but there is [the demo](http://deform2demo.repoze.org/).  In my experience, deform2 is not yet always the prettiest, but it is mostly functional at this point.

Pull requests, discussion & grumblings about bs3 in deform should probably be directed at [deform](https://github.com/Pylons/deform) rather than `deform_bootstrap` since that's where the effort will be going.  (And remember, the 'a' in 2.0a1 does mean 'alpha'.)

**Comment by disko** [comment]
Referring to the discussion on https://github.com/Kotti/Kotti/pull/277, `deform_bootstrap` won't be updated to Bootstrap 3 as `deform` 2 is already based on that itself.  This makes `deform_bootstrap` redundant.

**Comment by scott2b** [comment]
Didn't mean to come across as grumbling. Just a point of clarification of expectations. Also, I guess I didn't realize that bootstrap 3 rendering was being done in deform itself. Thanks for the reply.

**Comment by disko** [comment]
> Didn't mean to come across as grumbling.

You didn't! Apologies if I sounded harsh, English isn't my mother tongue. ;)

I didn't close the issue due to unwillingness to deal with, but just because `deform` 2 already does everything that's discussed here.

**Comment by dairiki** [comment]
@scott2b NP. Sorry if I came across as snarky.  (English is my mother tongue — that doesn’t mean I’m always good at it.)

**Comment by scott2b** [comment]
ha, no. It's all good. Thanks again!
